import { portkey } from "../gateway/portkeyClient.js";
import { AIResponseSchema } from "../schema/aiResponse.js";
import { validateDynamicSql } from "../guardrails/validateDynamicSql.js";
import { executeTool } from "../tools/toolFactory.js";
import { createToolContext } from "../tools/context.js";

export async function askAgent(question: string) {
  const context = createToolContext();

  const systemPrompt = `You are an inventory and pricing assistant.
You have access to tools that fetch live data. If you need to look up items, set "shouldContinue" to true and provide the search term in "toolInput".
You must respond with a JSON object that matches this strict schema:
{
  "answer": "Your response or reasoning here",
  "confidence": 0.9,
  "shouldContinue": true,
  "toolInput": "product search query text here"
}`;

  // 1. Model Gateway Call
  const response = await portkey.chat.completions.create({
    model: "claude-3-5-sonnet-20240620",
    max_tokens: 1000,
    system: systemPrompt,
    messages: [{ role: "user", content: question }],
  });

  const contentBlock = response.choices[0]?.message?.content;
  const rawText = Array.isArray(contentBlock) ? "" : contentBlock || "";

  try {
    // 2. Parse and Validate Schema Output
    const parsedData = JSON.parse(rawText);
    const validated = AIResponseSchema.parse(parsedData);

    // 3. Flow Gate & Interception Guardrail
    if (validated.shouldContinue) {
      const generatedQuery = validated.toolInput || question;

      // GUARDRAIL AT THE TOOL BOUNDARY: Validate what the model generated before execution
      if (!validateDynamicSql(generatedQuery)) {
        throw new Error(`Security Alert: Blocked malicious query generated by model: "${generatedQuery}"`);
      }

      // 4. Decoupled Tool Factory Execution
      const toolResult = executeTool("searchProducts", { query: generatedQuery }, context);
      
      return {
        answer: `System Registry Lookup Complete. Payload: ${JSON.stringify(toolResult)}`,
        status: "finalize",
        logs: context.logs
      };
    }

    return {
      answer: validated.answer,
      status: "finalize",
      logs: context.logs
    };

  } catch (err: any) {
    console.warn("Pipeline execution halted or failed structural parsing.");
    return {
      answer: err.message || rawText,
      status: "abort",
      logs: context.logs
    };
  }
}